export const MODULE_BOUNDARIES = [
  "auth",
  "users",
  "roles",
  "profiles",
  "workers",
  "employers",
  "organizations",
  "skills",
  "opportunities",
  "applications",
  "matching",
  "training",
  "verification",
  "trust",
  "work-management",
  "attendance",
  "agreements",
  "wage-ledger",
  "payments",
  "notifications",
  "messaging",
  "moderation",
  "disputes",
  "fraud",
  "analytics",
  "admin",
  "partners",
  "field-coordination",
  "audit",
  "consent"
] as const;

export type ModuleBoundary = (typeof MODULE_BOUNDARIES)[number];
